sudo: false

language: node_js

node_js:
  - '4'
  - '5'
  - '6'
  - '7'

git:
  depth: 1

cache:
  directories:
    - node_modules

branches:
  only:
  - master
  - /^greenkeeper-/

notifications:
  email: false

after_success: npm run coverage
